### ISSUE TITLE
Client error : Uncaught DOMException

### ISSUE THREAD

**Issue by Scely** [lowlighter/denolithic#18]
What: 
- Uncaught DOMException: Document.querySelector: '#' is not a valid selector
 
When:
- Clicking on navigator buttons

**Comment by lowlighter** [comment]
Try clearing your browser cache

**Comment by Scely** [comment]
Still their using Firefox 88.0.1 and Chromium 89.0.4382.0.

**Comment by lowlighter** [comment]
Should be fixed with d29325b 👍
